import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/prsentationdeyooreedone">PrsentationdeYooreedOne</Link>
        </li>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
        <li>
          <Link to="/prsentationdeyooreed">PrsentationdeYooreed</Link>
        </li>
        <li>
          <Link to="/lesvenementsdeyooreed">LesvenementsdeYooreed</Link>
        </li>
        <li>
          <Link to="/dtailevenement">Dtailevenement</Link>
        </li>
        <li>
          <Link to="/listedespartenaires">Listedespartenaires</Link>
        </li>
        <li>
          <Link to="/listedesoprateurs">Listedesoprateurs</Link>
        </li>
        <li>
          <Link to="/howtocontactus">Howtocontactus</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
